# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee7204933cafd1f78bc43f993434fb93d3448a08c38b85cee6cc62a1ed900d46b9204ee8e5aa5a8bd8e3a9c9859f5775c9c287c8b289eaf593d30ab98559ce5c

test:
  secret_key_base: 9754daf3f82daff5b8b95ce343ec37de41a877e471b1af60cf2a1c2fe161aa6d4c548b08fe2cef266c2bed48f6017f89d47765a4ac21485a61f330cc84a3661c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
